# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigBob < Formula
  desc "CLI utility to generate secure configurations"
  homepage "https://github.com/foomo/config-bob"
  version "0.7.4"

  on_macos do
    url "https://github.com/foomo/config-bob/releases/download/0.7.4/config-bob_0.7.4_darwin_amd64.tar.gz"
    sha256 "9966ba32c0f9d1cd9d54524f304da66e5de0dcd39081f891f9e33e476fa1aaad"

    def install
      bin.install "config-bob"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ConfigBob
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/config-bob/releases/download/0.7.4/config-bob_0.7.4_linux_amd64.tar.gz"
      sha256 "0f11e85c121f70129776ea2f3a591c73c628a2e72428941642f19f4b1d5a78e4"

      def install
        bin.install "config-bob"
      end
    end
  end

  def caveats
    <<~EOS
      config-bob -h
    EOS
  end
end
