# This file was generated by GoReleaser. DO NOT EDIT.
cask "config-bob" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "054788084c4ad98a2c650563966eac9e1c13ee5eb4e8913b4723063f7a9bb8bd"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "98c1f805f4402246c4ae435394a059a75fa18f7faf8c63eb6d1418e71587f60e"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b36a9f5eda8db916fff01d7deff4dfd957d7c24671fc66def37f2a0981aa5f5f"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee5260617b7c49b0893c04825c83f26e53440e7190fce752ca7b54a04370bc5c"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_linux_amd64.tar.gz"
    end
  end

  name "config-bob"
  desc "CLI utility to generate secure configurations"
  homepage "https://github.com/foomo/config-bob"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "config-bob"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/config-bob"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    config-bob -h
  EOS
end
