# This file was generated by GoReleaser. DO NOT EDIT.
cask "config-bob" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "d20de70c7e4f3f9acaaf086dbe8288689743300b968dff276bae01ab6b7a1245"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "351255f65b255c2a5ec74da1b15879e3597e60724d52749547045844d8d28f23"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d297bf8f1d143142c0c008177a5853ec1945b6cc98ccb353d2adc0f99149f67e"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ce485594f221be63a45a2f62f68fa0dafc6a6a9772b0c94b505136b25945fc41"
      url "https://github.com/foomo/config-bob/releases/download/v#{version}/config-bob_#{version}_linux_amd64.tar.gz"
    end
  end

  name "config-bob"
  desc "CLI utility to generate secure configurations"
  homepage "https://github.com/foomo/config-bob"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "config-bob"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/config-bob"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    config-bob -h
  EOS
end
